name: Node.js Package

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: '@0seo8'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

        env:
          NODE_AUTH_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
